### PR TITLE
Update mecab to mecab-python3

### PR DESCRIPTION
**Pull request by xia0nan**
Need to update mecab to mecab-python3 or installation will throw errors.

### CODE REVIEW

**Comment by ikegami-yukino** [comment]
@xia0nan 
What is this Pull-request?

**Comment by xia0nan** [comment]
@ikegami-yukino 
in the requirements.txt, one dependency is listed: **mecab**
but it will cause installation failure. 
it works if you change it to **mecab-python3** (https://pypi.org/project/mecab-python3/)

**Comment by ikegami-yukino** [comment]
@xia0nan 
What is an error message?
I will maintain the **mecab** module.

**Comment by xia0nan** [comment]
@ikegami-yukino 
you can try in google colab with the 
`!pip install oseti`
it will throw you error
```
Collecting mecab
  Downloading mecab-0.996.3.tar.gz (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 KB 4.7 MB/s eta 0:00:00
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
```

**Comment by ikegami-yukino** [comment]
@xia0nan 
This problem is that MeCab C++ library is not installed.

Please try bellow.
```
!apt install aptitude
```
```
!aptitude install mecab libmecab-dev mecab-ipadic-utf8 git make curl xz-utils file -y
```

**Comment by ikegami-yukino** [comment]
No replies, so I'm closing this PR...

**Pull request closed without merging**
